[package]
name = "dogfight"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dogfight-macros = { path = "dogfight-macros" }
ts-rs = "7.1.1"
