[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dogfight = { path = "../dogfight" }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
ts-rs = "7.1.1"
