// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityChangeType } from "./EntityChangeType";
import type { EntityType } from "./EntityType";

export interface EntityChange { ent_type: EntityType, id: number, update: EntityChangeType, }